# Generated by Django 4.0.3 on 2022-04-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
