# Generated by Django 4.0.3 on 2022-04-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_converter', '0002_currency_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('source_amount', models.FloatField()),
                ('source_money', models.CharField(max_length=3, verbose_name='source_money')),
                ('target_amount', models.FloatField()),
                ('target_money', models.CharField(max_length=3, verbose_name='target_money')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currency_converter.userprofile')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
            },
        ),
    ]
